language: objective-c
osx_image: xcode8
before_install:
  - sudo gem install xcpretty

script:
  - xcodebuild -project DotaComp.xcodeproj -scheme 'DotaComp' -sdk iphonesimulator build | xcpretty -c && exit ${PIPESTATUS[0]}
